name: Publish to pub.dev

on:
  workflow_call:
    inputs:
      working-directory:
        description: The directory within the repository where the package is located
        required: true
        type: string

jobs:
  publish:
    name: Publish to pub.dev
    runs-on: ubuntu-latest
    environment: pub.dev
    permissions:
      id-token: write # Required for authentication using OIDC

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1

      - name: Setup Dart SDK and provision OIDC token
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c #v1.7.1

        # This is a fork of subosito/flutter-action. The upstream version doesn't pin the action
        # it references hence we need to fork it to enforce the policy
      - name: Setup Flutter SDK - needed for publishing Flutter packages.
        uses: talkjs/flutter-action@408dece5e074567f0bb32ef68b82fe01ed5fdeac #1.0.0

      - name: Install dependencies
        run: dart pub get
        working-directory: ${{ inputs.working-directory }}

        # If the package has errors, it won't upload.
      - name: Publish
        run: dart pub publish --force
        working-directory: ${{ inputs.working-directory }}
